version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight.
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values

  - name: stg_addresses
    description: Addressess table
    columns:
      - name: address_id
        tests:
          - unique
          - not_null
  
  - name: stg_events
    description: Events table

  - name: stg_order_items
    description: Order items table
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
    tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
          - order_id
          - product_id
  
  - name: stg_orders
    description: Orders table
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null

  - name: stg_products
    description: Products table
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_promos
    description: Promos table
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null

  - name: stg_users
    description: Users table
    columns:
      - name: user_id
        tests:
          - unique
          - not_null