version: 2

models:

  - name: stg_addresses
    description: Addressess table
    columns:
      - name: address_id
        tests:
          - unique
          - not_null
  
  - name: stg_events
    description: Events table
    columns:
      - name: event_type
        tests:
        - accepted_values:
            values: ['add_to_cart', 'checkout', 'page_view', 'package_shipped']
            severity: warn

  - name: stg_order_items
    description: Order items table
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
    tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
          - order_id
          - product_id
  
  - name: stg_orders
    description: Orders table
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: status
        tests:
        - accepted_values:
            values: ['shipped', 'preparing', 'delivered']
            severity: warn

  - name: stg_products
    description: Products table
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_promos
    description: Promos table
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null

  - name: stg_users
    description: Users table
    columns:
      - name: user_id
        tests:
          - unique
          - not_null