version: 2

models:
  - name: int_users_first_order
    description: Get attributes for first order, drivers of repeat rate?
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
